[theme]
base="dark"
primaryColor="#FF4BBD"
backgroundColor="#283243"
secondaryBackgroundColor="#5b5e73"
# base="dark"
# primaryColor="#2d5fa2"
# backgroundColor="#22304e"
# secondaryBackgroundColor="#394173"
font="monospace"
